"""Data-size learning curve: retrain the advice adapter on nested subsets of the train split.

    uv run python scripts/run_subsets.py              # waits for the full run, then 150 → 300 → 600 → 900
    uv run python scripts/run_subsets.py --no-wait

A curve over training steps mixes "more rows" with "more passes at a different
learning rate". Separate runs per size answer the question directly: how good
does the detector get with N labelled rows?

Each size:
  - stratified by label, and nested (150 ⊂ 300 ⊂ 600 ⊂ 900), so sizes differ only by
    the rows added
  - the full run's hyperparameters unchanged (3 epochs, cosine, peak 2e-4), so steps
    scale with rows
  - a checkpoint and a val loss once per epoch
  - every checkpoint scored by eval_checkpoints.py on the same eval drafts as the
    full run
The 1,087-row point is the full run itself. Afterwards scripts/learning_report.py
writes reports/advice_learning_curve.md.

Resumable: a size whose adapter exists is not retrained, and scoring skips steps
already scored.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import random
import subprocess
import time
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CONFIG = ROOT / "configs" / "train_advice.yaml"
P = "personalised_recommendation"


def log(msg: str) -> None:
    print(f"[{time.strftime('%H:%M:%S')}] {msg}", flush=True)


def busy() -> bool:
    out = subprocess.run(["docker", "ps", "-q", "--filter", "ancestor=gj-train:latest"],
                         capture_output=True, text=True).stdout
    return bool(out.strip())


def run(cmd: list[str], log_path: Path) -> int:
    with log_path.open("w") as fh:
        return subprocess.run(cmd, cwd=ROOT, stdout=fh, stderr=subprocess.STDOUT).returncode


def nested_subsets(train_file: Path, sizes: list[int], seed: int) -> dict[int, list[str]]:
    lines = [l for l in train_file.read_text().splitlines() if l.strip()]
    label = lambda l: json.loads(json.loads(l)["messages"][2]["content"])["label"]
    pos = [l for l in lines if label(l) == P]
    neg = [l for l in lines if label(l) != P]
    rng = random.Random(seed)
    rng.shuffle(pos)
    rng.shuffle(neg)
    frac = len(pos) / len(lines)
    # Prefixes of one shuffle, so every smaller subset sits inside every larger one.
    return {n: pos[: round(n * frac)] + neg[: n - round(n * frac)] for n in sorted(sizes)}


def scored_steps(run_dir: Path) -> set[int]:
    path = run_dir / "curve.jsonl"
    return {json.loads(l)["step"] for l in path.read_text().splitlines() if l.strip()} if path.exists() else set()


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--sizes", type=int, nargs="+", default=[150, 300, 600, 900])
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--no-wait", action="store_true", help="don't wait for the full run to finish")
    ap.add_argument("--poll", type=int, default=120)
    args = ap.parse_args()

    cfg = yaml.safe_load(CONFIG.read_text())
    full_dir = ROOT / cfg["sft"]["output_dir"]
    if not args.no_wait:
        log(f"waiting for the full run ({full_dir.name}) and its scorer to finish")
        while not ((full_dir / "adapter_model.safetensors").exists() and not busy()):
            time.sleep(args.poll)
        log("full run finished")

    rows_per_step = cfg["sft"]["per_device_train_batch_size"] * cfg["sft"]["gradient_accumulation_steps"]
    epochs = cfg["sft"]["num_train_epochs"]
    subsets = nested_subsets(ROOT / cfg["data"]["train_file"], args.sizes, args.seed)

    for n, lines in subsets.items():
        run_dir = ROOT / "outputs" / "subsets" / f"n{n}"
        run_dir.mkdir(parents=True, exist_ok=True)
        data_path = ROOT / "data" / "processed" / "subsets" / f"advice_train_n{n}.jsonl"
        data_path.parent.mkdir(parents=True, exist_ok=True)
        shuffled = lines[:]
        random.Random(args.seed).shuffle(shuffled)
        data_path.write_text("".join(l + "\n" for l in shuffled))

        steps_per_epoch = math.ceil(n / rows_per_step)
        sub = copy.deepcopy(cfg)
        sub["data"]["train_file"] = str(data_path.relative_to(ROOT))
        sub["sft"]["output_dir"] = str(run_dir.relative_to(ROOT))
        sub["sft"]["eval_steps"] = sub["sft"]["save_steps"] = steps_per_epoch
        cfg_path = ROOT / "configs" / "subsets" / f"n{n}.yaml"
        cfg_path.parent.mkdir(parents=True, exist_ok=True)
        cfg_path.write_text(f"# Generated by scripts/run_subsets.py: configs/train_advice.yaml on a {n}-row subset.\n"
                            + yaml.safe_dump(sub, sort_keys=False))
        positives = sum(json.loads(json.loads(l)["messages"][2]["content"])["label"] == P for l in lines)

        if not (run_dir / "adapter_model.safetensors").exists():
            log(f"n={n} ({positives} personalised): training {steps_per_epoch * epochs} steps")
            started = time.monotonic()
            rc = run(["bash", "train/run.sh", "python", "-u", "train/train_advice.py",
                      "--config", str(cfg_path.relative_to(ROOT))], run_dir / "train.log")
            if rc:
                log(f"n={n}: training FAILED (exit {rc}) — see {run_dir / 'train.log'}")
                return rc
            log(f"n={n}: trained in {(time.monotonic() - started) / 60:.0f} min")

        ckpts = {int(d.name.split("-")[1]) for d in run_dir.glob("checkpoint-*")}
        if not ckpts <= scored_steps(run_dir):
            log(f"n={n}: scoring checkpoints {sorted(ckpts - scored_steps(run_dir))}")
            time.sleep(25)  # eval_checkpoints waits for a checkpoint's files to settle
            rc = run(["bash", "train/run.sh", "python", "-u", "scripts/eval_checkpoints.py",
                      "--config", str(cfg_path.relative_to(ROOT)), "--no-base"], run_dir / "score.log")
            if rc:
                log(f"n={n}: scoring FAILED (exit {rc}) — see {run_dir / 'score.log'}")
                return rc
        curve = [json.loads(l) for l in (run_dir / "curve.jsonl").read_text().splitlines() if l.strip()]
        final = max(curve, key=lambda p: p["step"])
        log(f"n={n}: final step {final['step']}  f1 {final['f1']:.3f}  recall {final['recall']:.3f}  "
            f"precision {final['precision']:.3f}  auc {final['auc'] or 0:.3f}")

    log("writing report")
    rc = run(["uv", "run", "--with", "matplotlib", "python", "scripts/learning_report.py"],
             ROOT / "outputs" / "subsets" / "report.log")
    log("report written: reports/advice_learning_curve.md" if rc == 0 else f"report FAILED (exit {rc})")
    log("queue done")
    return rc


if __name__ == "__main__":
    raise SystemExit(main())
